### ISSUE TITLE
Proof of concept: Java 17 migration ready for review

### ISSUE THREAD

**Issue by GG-Feng** [pf4j/pf4j#657]
﻿## Summary

I have prepared a proof of concept that migrates PF4J from Java 8 to Java 17. The migration branch is available at:

**Fork:** https://github.com/handsomewu6688-design/pf4j/tree/migrate-to-java-17

### Build Configuration
- Updated `maven.compiler.release` from 8 to 17
- Simplified the multi-release JAR compilation setup (the separate `java9-compile` execution for `module-info.java` is no longer needed since Java 17 is now the baseline)
- Upgraded `maven-surefire-plugin` from 2.22.1 to 3.2.5 (required for Java 17 class file support)
- Upgraded JaCoCo from 0.8.11 to 0.8.14
- Added `jakarta.annotation-api` 1.3.5 as provided dependency

### Source Code Modernization
- Applied Java 17 idioms: pattern matching for `instanceof`, `var` for local variables, etc.
- Modernized API usage where applicable

### Test Infrastructure Adaptation
- Fixed `JavaSources.compileAll()` to work with the module system by including both classpath and module path entries
- Added surefire configuration with `--add-opens` for module access

## Test Results

Local build with JDK 17 (Temurin 17.0.19):
- **Build: SUCCESS**
- **Tests: 289/302 PASS** (95.7%)

### Remaining Test Issues (13)
All 13 remaining test issues are related to Java module system behavior changes:

1. **PluginClassLoaderTest (6 failures):** Resource count assertions differ under Java 17 module classloading vs Java 8 classpath classloading. These are assertion differences, not functionality regressions.

2. **ExtensionAnnotationProcessorTest (6 errors):** `compile-testing` library encounters `module is null` errors when running annotation processors in the module path context. This is a known `compile-testing` + JPMS limitation.

3. **SingletonExtensionFactoryTest (1 error):** `NoClassDefFoundError: org/pf4j/ExtensionPoint` when loading classes via isolated URLClassLoaders in the module path context.

These issues require further investigation into test infrastructure adaptation for the module system, but do not represent regressions in PF4J core functionality.

## Motivation

Java 8 has been EOL since 2019 (free public updates). The broader ecosystem is moving to Java 17 as the new LTS baseline. This PoC demonstrates that the migration is technically feasible and most of the codebase works well with Java 17.

I am happy to refine this based on maintainer feedback and help address the remaining test infrastructure issues if there is interest in pursuing this migration.

## How to Review

```bash
git clone https://github.com/handsomewu6688-design/pf4j.git
cd pf4j
git checkout migrate-to-java-17
./mvnw clean test
```

**Comment by decebals** [comment]
Thank you for putting together this PoC - it is well documented and shows the migration is technically feasible.

That said, I decided not to go ahead with a Java 17 migration right now. PF4J is an infrastructure library used inside other applications, and raising the minimum JVM requirement would cut off users on Java 8 and Java 11 (still very common in enterprise) without adding real value for them. Code modernization gains like pattern matching and `var` are cosmetic for a framework that is already stable and mature.

The current setup - Java 8 baseline with a multi-release JAR for Java 9+ module support - already handles the module system and works across a wide range of JVM versions, which is a better fit for a library like this.

I would revisit this if specific Java 17+ features opened up genuinely new capabilities for PF4J users, but that is not the case right now.

Closing as not planned. Thanks again for the effort!
